# Generated by Django 4.2.7 on 2024-07-19 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="FIO (to'liq ism)")),
                ('date_of_birth', models.DateField(verbose_name="Tug'ilgan sana")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('residential_address', models.TextField(verbose_name='Yashash manzili')),
                ('registration_address', models.TextField(verbose_name='Propiska manzili')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('department', models.CharField(max_length=255, verbose_name="Kafedra/bo'lim")),
                ('education_level', models.CharField(choices=[('secondary', "O'rta maxsus"), ('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('candidate', 'Fan nomzodi'), ('doctor', 'Fan doktori'), ('other', 'Boshqa')], max_length=20, verbose_name="Ta'lim darajasi")),
                ('specialty', models.CharField(max_length=255, verbose_name='Mutaxassislik')),
                ('educational_institution', models.CharField(max_length=255, verbose_name="O'quv yurti")),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Bitirgan yil')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Malaka va ko'nikmalar")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Oldingi ish joyi')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_experiences', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hobbi va qiziqishlar')),
                ('social_media', models.URLField(blank=True, null=True, verbose_name='Ijtimoiy tarmoqlar')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Tashkilot nomi')),
                ('role', models.CharField(max_length=255, verbose_name='Rol')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="FIO (oila a'zosi)")),
                ('date_of_birth', models.DateField(verbose_name="Tug'ilgan sana")),
                ('relationship', models.CharField(default='qarindosh', max_length=255, verbose_name="Oila a'zosi munosabati")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Konferensiya/seminar nomi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sertifikat')),
                ('date', models.DateField(verbose_name='Sana')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mukofot')),
                ('date', models.DateField(verbose_name='Sana')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='app.employee')),
            ],
        ),
    ]
