# Generated by Django 4.2.7 on 2024-07-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Mukofot', 'verbose_name_plural': 'Mukofotlar'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikatlar'},
        ),
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': 'Konferensiya/seminar', 'verbose_name_plural': 'Konferensiyalar/seminarlar'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': "Oila a'zosi", 'verbose_name_plural': "Oila a'zolari"},
        ),
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'verbose_name': "Tashkilot a'zosi", 'verbose_name_plural': "Tashkilot a'zolari"},
        ),
        migrations.AlterModelOptions(
            name='personaldetail',
            options={'verbose_name': "Shaxsiy ma'lumot", 'verbose_name_plural': "Shaxsiy ma'lumotlar"},
        ),
        migrations.AlterModelOptions(
            name='professionalexperience',
            options={'verbose_name': 'Professional tajriba', 'verbose_name_plural': 'Professional tajribalar'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publikatsiya', 'verbose_name_plural': 'Publikatsiyalar'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': "Ko'nikma", 'verbose_name_plural': "Ko'nikmalar"},
        ),
        migrations.RenameField(
            model_name='familymember',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AddField(
            model_name='employee',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('phd', 'PhD'), ('dsc', 'DsC')], max_length=200, null=True, verbose_name='Ilmiy daraja'),
        ),
        migrations.AddField(
            model_name='employee',
            name='scientific_title',
            field=models.CharField(blank=True, choices=[('teacher_trainee', "o'qituvchisi stajyor"), ('teacher_assistant', "o'qituvchisi(assistent)"), ('senior_teacher', "katta o'qituvchis"), ('dotsent', 'dotsent'), ('professor', 'professor')], max_length=255, null=True, verbose_name='Ilmiy unvon'),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Vazifalar'),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education_level',
            field=models.CharField(choices=[('secondary_special', "O'rta maxsus"), ('secondary', "O'rta"), ('higher', 'Oliy')], max_length=20, verbose_name="Ta'lim darajasi"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='FIO (passport buycha)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registration_address',
            field=models.TextField(verbose_name="Ro'yhatdan o'tgan manzili"),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
    ]
